The ``101-lazy_matrix_mul.py`` module
======================

import the function:

       >>> matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

valide case:
       >>> matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
       array([[ 7, 10],
              [15, 22]])

       >>> matrix_mul([[1, 2]], [[3, 4], [5, 6]])
       array([[13, 16]])

invalid type:

       >>> matrix_mul([[1, 2]], "Hi")
       Traceback (most recent call last):
       ...
       ValueError: Scalar operands are not allowed, use '*' instead


       >>> matrix_mul("Hi", [[1, 2]])
       Traceback (most recent call last):
       ...
       ValueError: Scalar operands are not allowed, use '*' instead

type list of lists:

       >>> matrix_mul([[1, 2], [3, 4]], [[1, 2], "Hi"])
       Traceback (most recent call last):
       ...
       ValueError: setting an array element with a sequence


       >>> matrix_mul([[1, 2], "Hi"], [[1, 2], [3, 4]])
       Traceback (most recent call last):
       ...
       ValueError: setting an array element with a sequence

test empty:

       >>> matrix_mul([], [[1, 2], [3, 4]])
       Traceback (most recent call last):
       ...
       ValueError: shapes (0,) and (2,2) not aligned: 0 (dim 0) != 2 (dim 0)

       >>> matrix_mul([[1, 2], [3, 4]], [[]])
       Traceback (most recent call last):
       ...
       ValueError: shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

invalid type:

       >>> matrix_mul([[1, 2], [3, "hi"]], [[1, 2], [3, 4]])
       Traceback (most recent call last):
       ...
       TypeError: invalid data type for einsum

       >>> matrix_mul([[1, 2], [3, 4]], [['T', 2], [3, 4]])
       Traceback (most recent call last):
       ...
       TypeError: invalid data type for einsum

test size:

       >>> matrix_mul([[1, 2], [3]], [[1, 2], [3, 4]])
       Traceback (most recent call last):
       ...
       ValueError: setting an array element with a sequence.

       >>> matrix_mul([[1, 2], [3, 4]], [[1, 2], [4]])
       Traceback (most recent call last):
       ...
       ValueError: setting an array element with a sequence.

test mul:

       >>> matrix_mul([[1, 2, 3], [4, 5, 6]], [[1, 2], [3, 4]])
       Traceback (most recent call last):
       ...
       ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

Missing arguments:

	>>> lazy_matrix_mul()
	Traceback (most recent call last):
	...
	TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'

	>>> lazy_matrix_mul([3])
	Traceback (most recent call last):
	...
	TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'
